# #PCA of environmental data in R
# Used http://www.r-bloggers.com/computing-and-visualizing-pca-in-r/ as a guide


library(devtools)
install_github("ggbiplot", "vqv")
library(ggbiplot)
library(dplyr)
library(tidyr)

#CLear out everything from the environment
rm(list=ls())


##################
#################
###DATA ENTRY AND CLEANUP
##################
#################
#Step 1: load the individual CSV files and save them as dataframes
setwd("/Users/emiliobruna/Dropbox/Alan/Data/Capitulo2")
NEST.DATA<-read.csv("ActiveNests_data_2-3-4-5-6.csv", dec=".", header = TRUE, sep = ",", check.names=FALSE )
VEG<-read.csv("ActiveNests_CensoVeg_1.csv", dec=".", header = TRUE, sep = ",", check.names=FALSE )
AIRTEMPHUMID<-read.csv("ActiveNests_TempAirHumid_7.csv", dec=".", header = TRUE, sep = ",", check.names=FALSE )
#make plot locations an ordered factor nest<adjacent<far
NEST.DATA$location=factor(NEST.DATA$location, levels=c("nest","adjacent", "far"), ordered=TRUE)


head(NEST.DATA, 3)
str(NEST.DATA)

# #Select only Cerrado Denso and Cerrado Ralo
NEST.DATA.both<-filter(NEST.DATA, habitat =="CD" | habitat == "CR")
# #Select only Cerrado Denso 
NEST.DATA.CD<-filter(NEST.DATA, habitat =="CD")
#Select only Cerrado Ralo
NEST.DATA.CR<-filter(NEST.DATA, habitat == "CR")
# 
# Which of the habitats are you going to analyze? CD, CR, or both?
NEST.DATA.PCA<-NEST.DATA.both #NEST.DATA.CD NEST.DATA.both NEST.DATA.CR 
#Delete the ones with missing values. 
#Note there are techniques to impute missing values can look into 
NEST.DATA.PCA<-na.omit(NEST.DATA.PCA) 
# log transform 
# env.vars <- log(NEST.DATA.PCA[, 5:18]+1)
# no transformation as per HLV
env.vars <- NEST.DATA.PCA[,5:18]
site.cats <- NEST.DATA.PCA[, 1:4]

# Exclude the following: grass biomass, canopy.cover, deep soil humidity 
env.vars$perc.cover<-NULL
env.vars$grass.bmass<-NULL
env.vars$humid.soil.deep<-NULL
env.vars$peak.soil.temp<-NULL



# apply PCA - scale. = TRUE is highly advisable, but default is FALSE. 
nest.env.pca <- prcomp(env.vars,
                 center = TRUE,
                 scale. = TRUE) 

#Visualizing the results.
# The print method returns the standard deviation of each of the four PCs, 
# and their rotation (or loadings), which are the coefficients of the linear combinations of the continuous variables.
print(nest.env.pca)


# The Figure below is useful to decide how many PCs to retain for further analysis. 
# I.E., which PCs explain most of the variability in the data.
plot(nest.env.pca, type = "l")

# The summary method describe the importance of the PCs. 
# The first row describe again the standard deviation associated with each PC. 
# The second row shows the proportion of the variance in the data explained by each component.
# The third row describe the cumulative proportion of explained variance. 
# summary method
summary(nest.env.pca)




# The Figure below is a biplot generated by the function ggbiplot of the ggbiplot package available on https://github.com/vqv/ggbiplot
# TO install: 
# library(devtools)
# install_github("ggbiplot", "vqv")
# library(ggbiplot)
# ?ggbiplot for more info on arguments you can change and % used to draw ellipses aroudnd points
g <- ggbiplot(nest.env.pca, obs.scale = 1, var.scale = 1, 
              groups = site.cats$location, ellipse = TRUE, 
              circle = TRUE)
g <- g + scale_color_discrete(name = '')
g <- g + theme(legend.direction = 'horizontal', 
               legend.position = 'top')
print(g)
